apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-statefulset
spec:
  serviceName: "db-service"
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      initContainers:
      - name: init-db
        image: busybox
        command: ["sh", "-c", "if [ -e /dsb/backup/example.txt ]; then echo 'Plik istnieje'; cp -r /dsb/backup/* /data/db/; else echo 'Plik nie istnieje'; fi"]
        volumeMounts:
        - name: db-backup
          mountPath: /dsb/backup
        - name: db-data
          mountPath: /data/db
      containers:
      - name: database
        image: mongo:latest
        ports:
        - containerPort: 27017
      volumes:
      - name: db-backup
        persistentVolumeClaim:
          claimName: backup-pvc
      - name: db-data
        persistentVolumeClaim:
          claimName: data-pvc
