apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: init-db
        image: busybox
        command: ["sh", "-c", "if [ -e /dsb/backup/example.txt ]; then echo 'Plik istnieje'; cp -r /dsb/backup/* /data/db/; else echo 'Plik nie istnieje'; fi"]
        volumeMounts:
        - name: db-backup
          mountPath: /dsb/backup
        - name: db-data
          mountPath: /data/db
      containers:
      - name: backend
        image: backend-deployment-image:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /isAlive
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /isReady
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
      volumes:
      - name: db-backup
        persistentVolumeClaim:
          claimName: backup-pvc
      - name: db-data
        persistentVolumeClaim:
          claimName: data-pvc
