apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace.name}}
  name: backend-service
spec:
  type: {{.Values.service.type}}
  selector:
    app: {{.Values.image.type}}
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetport: {{.Values.service.port}}
      nodePort: 30009