# Backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-backend
  namespace: fiszki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-service
          image: fiszki_backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: LOGGING_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: logging
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DATABASE_URL

---
# Access to backend from the browser
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fiszki
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 30001
  type: LoadBalancer
