apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backend
  namespace: fiszki
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/pv-backend/
  claimRef:
    namespace: fiszki
    name: backend-volume-claim
