apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-volume-claim
  namespace: fiszki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: standard
