apiVersion: v1
kind: Service
metadata:
  name: mongo-db-sv
  namespace: fiszki
  labels:
    app: mongodb
spec:
  ports:
    - protocol: TCP
      port: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db-ss
  namespace: fiszki
spec:
  serviceName: "mongo-db-sv"
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: backend-volume
              mountPath: /data/db
      volumes:
        - name: backend-volume
          persistentVolumeClaim:
            claimName: backend-volume-claim
