apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-volume
  namespace: fiszki
  labels:
    type: local
spec:
  claimRef:
    namespace: fiszki
    name: backup-volume-claim
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-volume-claim
  namespace: fiszki
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
