apiVersion: apps/v1
kind: Deployment
metadata:
  name: bend-deploy
  namespace: apka
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: fiszki-bend
        image: fiszki_bend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
    volumes:
      - name: pv_backend
        persistentVolumeClaim:
          claimName: log-volume-claim
