apiVersion: apps/v1
kind: Deployment
metadata:
  name: bend-deploy
  namespace: apka
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: fiszki-bend
        image: fiszki_bend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /isAlive
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /isReady
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: pv-backend
          mountPath: /data/pv_backend/
      volumes:
      - name: pv-backend
        persistentVolumeClaim:
          claimName: log-volume-claim

