apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: apka
  labels:
    app: backend
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: pv-backend
          persistentVolumeClaim:
            claimName: backend-volume-claim
      containers:
        - name: backend
          image: fiszki_backend:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
          - containerPort: 8000
            name: backend-port
          env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: backend-configmap
                key: databaseUrl
          - name: logging
            valueFrom:
              configMapKeyRef:
                name: backend-configmap
                key: logging
          volumeMounts:
            - mountPath: "/app/loggs"
              name: pv-backend

# #minikube start
# #kubectl get namespaces
# #kubectl config set-context --current --namespace=apka
# #eval $(minikube docker-env)
# #docker build -t fiszki_backend:latest fiszki_backend/
# #kubectl apply -f kubernetes_yamls/
# minikube service backend --namespace=apka

# poprawne działanie probe'ów widać w logach w dashboardzie
# kubectl logs db-statefulset-0 -c check-file
# network policy jeszcze nie przetestowane - calico nie działa XDDD

