apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backend
  namespace: apka
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/pv-backend/
  claimRef:
    name: backend-volume-claim
    namespace: apka