apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{.values.namespace.name}}
  labels:
    app: {{.values.image.type}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.values.image.type}}
  template:
    metadata:
      labels:
        app: {{.values.image.type}}
    spec:
      containers:
      - name: fiszki-backend
        image: {{.values.image.image}}
        imagePullPolicy: {{.values.image.imagePullPolicy}}
        ports:
        - containerPort: {{.values.service.port}}
        env: 
          - name: MONGODB_HOST
            value: mongo-service