apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-backend
  namespace: {{.Release.Namespace}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-service
          image: "fiszki_backend:{{.Values.image.tag}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "mongodb://db-service:27017"
          livenessProbe:
            httpGet:
              path: /isAlive
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /isReady
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20