apiVersion: v1
kind: Service
metadata:
  namespace: apka
  name: db-service
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017