apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-lab3
  namespace: pv-yaml-lab3
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi