apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: apka
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      targetPort: backend-port
      port: 8000
      nodePort: 30005
