apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{.Values.namespace.name}}
  labels:
    app: fiszki_backend
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: fiszki_backend
  template:
    metadata:
      labels:
        app: fiszki_backend
    spec:
      containers:
      - name: backend-service
        image: "{{.Values.backend.image.repository}}:{{.Values.backend.image.tag}}"
        imagePullPolicy: {{.Values.backend.image.pullPolicy}}
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "mongodb://172.22.224.1:27017"