apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace.name}}
  name: backend-service
spec:
  type: NodePort
  selector:
    app: fiszki_backend
  ports:
    - protocol: TCP
      port: 8000
      nodePort: {{.Values.backend.service.nodePort}}