apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: apka
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-service
        image: fiszki_backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
