apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv_backend
spec:
  capacity:
    storage: 0.5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/pv_backend/ 
claimRef:
  name: pv_backend
  namespace: laby-trzeecie