version: '3.8'

services:
  backend:
    build:
      context: C:\Users\kryCyg\Documents\docker\devops-labs\projekt_do_pracy_na_labach\
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mongodb://db:27017"

  frontend:
    build:
      context: C:\Users\kryCyg\Documents\docker\devops-labs\projekt_do_pracy_na_labach\fiszki_app
    ports:
      - "8000:8000"

  db:
    image: mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
