apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: moj-namespace
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: db-container
        image: baza_danych_1
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 500m 
            memory: 512Mi  
          requests:
            cpu: 200m   
            memory: 256Mi  