apiVersion: v1
kind: Service
metadata:
  namespace: moj-namespace
  name: db-service
spec:
  selector:
    app: database
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
