apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backend
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv_backend/
