apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: namespace2
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-backup
            image: mongo
            command: ["sh", "-c", "mongodump --host mongodb-service-0.mongodb-service --db fiszki --out /backup/$(date +%Y-%m-%d_%H-%M-%S)"]
          restartPolicy: OnFailure
