apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backend
  namespace: app-namespace
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv-backend/
  claimRef:
    name: pv-backend-claim
    namespace: app-namespace