apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: app-namespace
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 30005