apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: lab2
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: dp-port
      