apiVersion: v1
kind: Service
metadata:
  name: mongo-db-service
  namespace: app-namespace
spec:
  type: ClusterIP
  selector:
    app: mongo-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017