apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: namespace2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: pv-backend-claim
      containers:
      - name: backend
        image: krycyg/repozytorium:fiszki_backend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_URL
        - name: LOGGING_MODE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: logging
        volumeMounts:
          - mountPath: /var/log
            name: log-volume
