apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: namespace2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: krycyg/repozytorium:fiszki_backend
        ports:
        - containerPort: 8000
