version: '3.8'
services:
  frontend:
    build: ./fiszki_app
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./fiszki_backend
    environment:
      - DATABASE_URL=mongodb://db:27017/baza_danych_1
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data: 

networks:
  app-network: 
