apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv_backend
spec:
  claimRef:
    namespace: default
    name: pv_backendc
  capacity:
    storage: 600Mi
  accessModes:
      - ReadWriteOnce
  hostPath:
    path: /data/pv_backend/