apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-backend-claim
  namespace: lab2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi