apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backend
  namespace: samczuk
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /data/pv-backend/
  claimRef:
    name: pv-backend-claim
    namespace: samczuk
