apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-backend-claim
  namespace: namespace2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi 
  storageClassName: standard
