apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: lab2
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: backend-port
      nodePort: 30010