apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80  # Gdzie apka na serwerze klastra
      targetPort: 8000 # Gdzie apka wewnątrz kont
      NodePort: 50001 # Port na serwerze klastra