apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: namespace2
spec:
  selector:
    app: backend
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30001
