apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefullset-db
  namespace: samczuk
spec:
  serviceName: "mongo-db"
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-service
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: pv-backend
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: pv-backend-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
