apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefullset-db
  namespace: lab2
spec:
  serviceName: "mongo-db"
  replicas: 2
  selector:
    matchLabels:
      app: db
      role: database
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-service
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: pv-backend
          mountPath: /data/db
      initContainers:
        - name: check-backup
          image: busybox:latest
          command: ["sh", "-c", "if [ -e /data/backup/example.txt ]; then cp -r /data/backup /data/db; else echo 'Plik nie istnieje'; fi"]
          volumeMonunts:
          - name: backup-volmue
            mountPath: /data/backup
  volumeClaimTemplates:
  - metadata:
      name: pv-backend-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
