apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-config
data:
  mongo-url: mongo-service
  DATABASE_URL: mongodb://fiszki-backend:27017
  logging: INFO # albo DEBUG
  
  # w przypadku chęci posiadania obu w jednym miejscu:
  # logging: |
  #   INFO
  #   DEBUG
  #  logging: "INFO, DEBUG"