apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
  labels:
    app: database
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
          name: db-port
        volumeMounts:
        - mountPath: "data/db"
          name: log-volume-claim
    initContainers:
        - name: check-backup
          image: busybox:latest
          command: ["sh", "-c", "if [ -e /dsb/backup/example.txt ]; then echo 'Plik istnieje'; else echo 'Plik nie istnieje'; fi"]
          volumeMounts:
          - name: backup-volume
            mountPath: /data/backup
  volumeClaimTemplates:
  - metadata:
      name: log-volume-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi