apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
spec:
  containers:
  - name: moj-backend
    image: fiszki_backend
    ports:
    - containerPort: 8000
    livenessProbe:
      httpGet:
        path: /isAlive
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 30
    readinessProbe:
      httpGet:
        path: /isReady
        port: 8000
      initialDelaySeconds: 20
      periodSeconds: 20
