apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80  # Port, na którym będzie dostępna aplikacja na serwerze klastra
      targetPort: 8000  # Port, na którym działa aplikacja wewnątrz kontenera
      nodePort: 30011  # Dowolny dostępny port na serwerze klastra
