apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: lab31
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-serviceee
          image: fiszki_backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data-volume    
              mountPath: /app
      volumes:
        - name: backend-volume
          persistentVolumeClaim:
            claimName: task-pv-claim

# kubectl apply -f backend-deployment.yaml
# kubectl get deployments
# kubectl get pods
# kubectl describe deployment backend-deployment

# kubectl apply -f backend-service.yaml
# minikube service backend-service

# kubectl delete deployments --all

# kubectl create namespace laby21
# kubectl config set-context --current --namespace=laby21

#kubectl delete service backend-service

# laby21

