version: '3.8'
services:
  frontend:
    image: fiszki_app:v1
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: fiszki_backend:v1
    ports: 
      - 8000:8000
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  db:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:
networks:
  app-network: