apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: app-namespace
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - protocol: TCP
      targetPort: db-port
      port: 27017