apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-service
          image: fiszli_backend:latest
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /isAlive
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /isReady
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
      volumes:
        - name: backend-data
          persistentVolumeClaim:
            claimName: database
