apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv_backend
spec:
  claimRef:
    namespace: default
    name: pv_backend
  accessModes:
      - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv_backend/
