apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-backend_v2 #zmienione nazwy
  namespace: pv_backend_l3
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi