apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backend
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/pv_backend/
  claimRef:
     name: pvc_backend
     namespace: apka