apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-backend
  namespace: apka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard
