apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv_backend
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi # Zmniejszamy ilość zapisywanej pamięci na mniejszą niż 1Gi
  hostPath:
    path: /data/pv_backend/ # Ustawienie ścieżki zapisu danych na hoscie
