
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backend
  namespace: default 
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path:  /data/pv_backend/
 
