apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backend
  namespace: apka
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: /data/pv_backend/
  claimRef:
    name: pv-claim
    namespace: apka
