apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
  labels:
    type: local
spec:
  claimRef:
     namespace: default
     name: log-volume-claim
  storageClassName: manual
  capacity:
    storage: 600Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"


