apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-backend-claim
  namespace: app-namespace
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi