apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backend
  namespace: lab
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 750Mi
  hostPath:
    path: /data/pv-backend/
  claimRef:
    name: pv-claim
    namespace: lab
