apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backend
  namespace: lab2  
spec:
  capacity:
    storage: 500Mi  
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv_backend/  
  claimRef:
    name: pvc-backend 
    namespace: lab2  
