apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv_mongo/"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backup
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv_backup/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

