apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: lab
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 750Mi