apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: apka
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 30001
