apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: MongoStatefullSet  
spec:
  serviceName: "mongodb"  
  replicas: 2
  selector:
    matchLabels:
      app: mongodb        
  template:
    metadata:
      labels:
        app: mongodb     
    spec:
      containers:
      - name: mongo      
        image: mongo:latest 
        ports:
        - containerPort: 27017   
          name: mongo
        volumeMounts:
        - name: pv_backend    
          mountPath: /data/db   
        envFrom:
        - configMapRef:
          name: backend-config
  volumeClaimTemplates:
  - metadata:
      name: data-volume  
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi   # Zmieniamy wymagania pamięci na 500Mi
# 