apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set
spec:
  serviceName: "mongodb"
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: pv-backend
          mountPath: /data/db
      initContainers:
      - name: check-backup
        image: busybox:latest
        command: ["sh", "-c", "if [ -e /data/backup/example.txt ]; then cp -r /data/backup /data/db; else echo 'Plik nie istnieje'; fi"]
  volumeClaimTemplates:
  - metadata:
      name: db-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi